# Matrix Build Declaration
language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Release PACKAGE=3.4 USE_LIBCXX=OFF
  - BUILD_TYPE=Release PACKAGE=3.5 USE_LIBCXX=OFF
  - BUILD_TYPE=Release PACKAGE=3.6 USE_LIBCXX=OFF
  - BUILD_TYPE=Release PACKAGE=4.8 USE_LIBCXX=OFF
  - BUILD_TYPE=Release PACKAGE=4.9 USE_LIBCXX=OFF
  - BUILD_TYPE=Debug PACKAGE=3.4 USE_LIBCXX=OFF
  - BUILD_TYPE=Debug PACKAGE=3.5 USE_LIBCXX=OFF
  - BUILD_TYPE=Debug PACKAGE=3.6 USE_LIBCXX=OFF
  - BUILD_TYPE=Debug PACKAGE=4.8 USE_LIBCXX=OFF
  - BUILD_TYPE=Debug PACKAGE=4.9 USE_LIBCXX=OFF

# We don't want a version mismatch between gcc and clang
matrix:
  # temporary, to be removed when scripts are building correctly
  fast_finish: true
  exclude:
    - { compiler: clang, env: BUILD_TYPE=Release PACKAGE=4.8 USE_LIBCXX=OFF }
    - { compiler: clang, env: BUILD_TYPE=Release PACKAGE=4.9 USE_LIBCXX=OFF }
    - { compiler: clang, env: BUILD_TYPE=Debug PACKAGE=4.8 USE_LIBCXX=OFF }
    - { compiler: clang, env: BUILD_TYPE=Debug PACKAGE=4.9 USE_LIBCXX=OFF }
    - { compiler: gcc, env: BUILD_TYPE=Release PACKAGE=3.4 USE_LIBCXX=OFF }
    - { compiler: gcc, env: BUILD_TYPE=Release PACKAGE=3.5 USE_LIBCXX=OFF }
    - { compiler: gcc, env: BUILD_TYPE=Release PACKAGE=3.6 USE_LIBCXX=OFF }
    - { compiler: gcc, env: BUILD_TYPE=Debug PACKAGE=3.4 USE_LIBCXX=OFF }
    - { compiler: gcc, env: BUILD_TYPE=Debug PACKAGE=3.5 USE_LIBCXX=OFF }
    - { compiler: gcc, env: BUILD_TYPE=Debug PACKAGE=3.6 USE_LIBCXX=OFF }

branches:
  only: master

# Environment Setup (Fixing Travis-CI, effectively)
before_install: python ./scripts/python/travis-before-install.py
install: python ./scripts/python/travis-install.py

# Configure, Build, Test Steps
before_script: python ./scripts/python/travis-configure.py
script: python ./scripts/python/travis-build.py

after_failure: python ./scripts/python/travis-failure.py
