# Matrix Build Declaration
language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Release PACKAGE=3.4
  - BUILD_TYPE=Release PACKAGE=3.5
  - BUILD_TYPE=Release PACKAGE=3.6
  - BUILD_TYPE=Release PACKAGE=4.8
  - BUILD_TYPE=Release PACKAGE=4.9
  - BUILD_TYPE=Debug PACKAGE=3.4
  - BUILD_TYPE=Debug PACKAGE=3.5
  - BUILD_TYPE=Debug PACKAGE=3.6
  - BUILD_TYPE=Debug PACKAGE=4.8
  - BUILD_TYPE=Debug PACKAGE=4.9

# We don't want a version mismatch between gcc and clang
matrix:
  exclude:
    - { compiler: clang, env: BUILD_TYPE=Release PACKAGE=4.8 }
    - { compiler: clang, env: BUILD_TYPE=Release PACKAGE=4.9 }
    - { compiler: clang, env: BUILD_TYPE=Debug PACKAGE=4.8 }
    - { compiler: clang, env: BUILD_TYPE=Debug PACKAGE=4.9 }
    - { compiler: gcc, env: BUILD_TYPE=Release PACKAGE=3.4 }
    - { compiler: gcc, env: BUILD_TYPE=Release PACKAGE=3.5 }
    - { compiler: gcc, env: BUILD_TYPE=Release PACKAGE=3.6 }
    - { compiler: gcc, env: BUILD_TYPE=Debug PACKAGE=3.4 }
    - { compiler: gcc, env: BUILD_TYPE=Debug PACKAGE=3.5 }
    - { compiler: gcc, env: BUILD_TYPE=Debug PACKAGE=3.6 }

branches:
  only: master

# Environment Setup (Fixing Travis-CI, effectively)
before_install: python ./scripts/travis-before-install.py
install: python ./scripts/travis-install.py

# Configure, Build, Test Steps
before_script: python ./scripts/travis-configure.py
script: python ./scripts/travis-build.py

after_failure: python ./scripts/travis-failure.py
